---
- name: Create the configurations for ENT sites
  template: src=ent.conf.j2 dest={{nginx_conf_dir}}/sites-available/{{ item.key }}.conf
  when: ent_sites is defined
  tags: [ent,nginx,entnonha]

- name: Create links for ENT sites
  file: state=link src={{nginx_conf_dir}}/sites-available/{{ item.key }}.conf dest={{nginx_conf_dir}}/sites-enabled/{{ item.key }}.conf
  when: ent_sites is defined
  notify:
   - reload nginx
  tags: [ent,nginx,entnonha]
